# -*- coding: utf-8 -*-
"""tinyML_header_gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SkJS1LGeV-g15RpslW1T7GY9UHD5de65
"""

pip install micromlgen

from micromlgen import port

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv("/content/biogas_rtdb_processed.csv")

features = ['temperature', 'humidity', 'extTemp', 'extHum', 'pressure']
target = 'V_ch4'

df = df.dropna(subset=features + [target])
df.head()

X = df[features].values
y = df[target].values
print(X.shape)
print(y.shape)
print(X)
print(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=True
)

rf_model = RandomForestRegressor(
    n_estimators=10,
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    n_jobs=-1,
    random_state=42
)

rf_model.fit(X_train, y_train)

sample = X_test[200]
print("Actual:", y_test[641])
print("Pred:", rf_model.predict([sample])[0])

y_pred = rf_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(y_test, y_pred)
r2   = r2_score(y_test, y_pred)

print(f"MSE: {mse:.6f}")
print(f"RMSE: {rmse:.6f}")
print(f"MAE : {mae:.6f}")
print(f"R²  : {r2:.4f}")

tinyML = port(rf_model, class_name="BiogasRFModel", indent=4)

with open("biogas_rf_modelv0.2.1.h", "w") as f:
    f.write(tinyML)

print("Saved model as biogas_rf_modelv0.2.1.h")

